// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJu6bXMOi6-vfMEy0eMbAiSP4kt3oNE7U',
    appId: '1:671949628227:web:73f079e5e0622a13d445f6',
    messagingSenderId: '671949628227',
    projectId: 'geoinfo-firebase',
    authDomain: 'geoinfo-firebase.firebaseapp.com',
    storageBucket: 'geoinfo-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASdRmxsS6v058KMyVeMFj4CsgK4A4rFhU',
    appId: '1:671949628227:android:6087456e7c264336d445f6',
    messagingSenderId: '671949628227',
    projectId: 'geoinfo-firebase',
    storageBucket: 'geoinfo-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiR3AZaQhxTzj80aYA4e-C9zCsjcUB6x0',
    appId: '1:671949628227:ios:be10b4faf2636bbad445f6',
    messagingSenderId: '671949628227',
    projectId: 'geoinfo-firebase',
    storageBucket: 'geoinfo-firebase.appspot.com',
    iosBundleId: 'com.example.rupestreFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiR3AZaQhxTzj80aYA4e-C9zCsjcUB6x0',
    appId: '1:671949628227:ios:064019beb08f652ed445f6',
    messagingSenderId: '671949628227',
    projectId: 'geoinfo-firebase',
    storageBucket: 'geoinfo-firebase.appspot.com',
    iosBundleId: 'com.example.rupestreFlutter.RunnerTests',
  );
}
